### ISSUE TITLE
TypeError: replace() takes at least 2 arguments (1 given)

### ISSUE THREAD

**Issue by Neato-Nick** [AppliedBioinformatics/PAV_table_scripts#2]
Hi, I'm trying to run makePAV.py and got this error

```
Traceback (most recent call last):
  File "makePAV.py", line 30, in <module>
    name = name.replace('Parent=',)
TypeError: replace() takes at least 2 arguments (1 given)
```

I went to line 30 and changed
`name = name.replace('Parent=',)`
to
`name = name.replace('Parent=','')`

But my output.tsv doesn't have content in it, just two lines of header:
```
Individual
<per-base bed_vs_exons.bed>
```

I tried running with and without the subbed `replace` arg, and using both python 2.7 and python 3.
I followed the rest of your protocol exactly, and the per-base output looks good. I can share with you over e-mail if you'd like to try it. Thanks,

**Comment by Neato-Nick** [comment]
I fixed the issue. Line 12 needs to match the features extracted to analyze.
On github it's set to 'CDS' but in the textbook chapter we are instructed to use exon.

Changing line 17 as I mentioned to fix replace() and changing line 12 to this does result in the expected output.
`if ll[7] != 'exon': continue`

**Comment by caiobrunharo** [comment]
I am getting a similar error but can't figure out how to fix the issue. Thoughts anyone?

Reference bed:
1_scaff        0       579     .       .       -       exon    .       transcript_id=LOLMU_00028049-RA;gene_id=LOLMU_00028049
1_scaff        2552    2849    .       .       +       exon    .       transcript_id=LOLMU_00028050-RA;gene_id=LOLMU_00028050
1_scaff        68115   70585   .       .       +       exon    .       transcript_id=LOLMU_00028051-RA;gene_id=LOLMU_00028051
1_scaff        74983   75600   .       .       +       exon    .       transcript_id=LOLMU_00028051-RA;gene_id=LOLMU_00028051


sample bed:
1_scaff        240     258     2       1_RagTag        exon    1       579     .       -       .       transcript_id=LOLMU_00028049-RA;gene_id=LOLMU_00028049; 18
1_scaff        258     342     4       1_RagTag        exon    1       579     .       -       .       transcript_id=LOLMU_00028049-RA;gene_id=LOLMU_00028049; 84
